DROP TABLE IF EXISTS BASIC;

CREATE TABLE BASIC (
    ID BIGINT,
    NAME VARCHAR(80)
);

--------------------------------------
DROP TABLE IF EXISTS FUNCTIONS;

CREATE TABLE FUNCTIONS (
   FUNVERSION VARCHAR(10),
   FUNLANGUAGE VARCHAR(30),
   FUNTIMESTAMP TIMESTAMP
);